language: python
python:
  - "2.6"
  - "2.7"
install:
  - sudo apt-get install nagios3  sudo apt-get install nagios3 check-mk-livestatus 
  - pip install unittest2==0.5.1 --use-mirrors
  - pip install coveralls --use-mirrors
  - python setup.py build
  - python setup.py install
  - sudo pynag config --append "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus"
  - sudo service nagios3 reload
before_script:
  - env
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Travis"
script:
  - coverage run --source=pynag tests/test.py
after_success:
  - coveralls
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pynag"
    on_failure: always
    on_success: change

