language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get -y install nagios3 check-mk-livestatus
  - pip install unittest2==1.1.0
  - pip install coveralls
  - python setup.py build
  - python setup.py install
  - sudo chmod 777 /etc/nagios3/nagios.cfg
  - sudo chmod a+rx '/var/cache/nagios3/'
  - echo "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus" >> /etc/nagios3/nagios.cfg
  - sudo service nagios3 reload
before_script:
  - env
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Travis"
script:
  - coverage run --source=pynag tests/test.py
after_success:
  - coveralls
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pynag"
    on_failure: always
    on_success: change

